#!/usr/bin/env python3
"""
Post a review comment on a GitHub PR and optionally push fix commits.

Usage:
    # Report only (comment on PR)
    python tools/gh_post_review.py --repo owner/repo --pr 42 \
        --analysis .tmp/pr-42/analysis.json

    # Fix and push
    python tools/gh_post_review.py --repo owner/repo --pr 42 \
        --analysis .tmp/pr-42/analysis.json \
        --fixes .tmp/pr-42/fixes_applied.json \
        --push-fixes

Requires:
    GITHUB_TOKEN in .env with repo scope (and write access for pushing)
"""

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

import requests
from dotenv import load_dotenv

load_dotenv()

GITHUB_API = "https://api.github.com"

CATEGORY_LABELS = {
    "P0": "Security",
    "P1": "Bugs",
    "P2": "Lint & Formatting",
    "P3": "Dead Code",
    "P4": "Code Smells",
    "P5": "Performance",
    "P6": "Tests",
    "P7": "Documentation",
}

CATEGORY_EMOJI = {
    "P0": "🔴",
    "P1": "🟠",
    "P2": "🟡",
    "P3": "🟡",
    "P4": "🔵",
    "P5": "🔵",
    "P6": "⚪",
    "P7": "⚪",
}


def get_headers():
    token = os.getenv("GITHUB_TOKEN")
    if not token:
        print("ERROR: GITHUB_TOKEN not found in .env", file=sys.stderr)
        sys.exit(1)
    return {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
    }


def build_review_body(analysis: dict, fixes: dict | None) -> str:
    total = analysis["total_issues"]
    auto_fixed = fixes["total_fixes"] if fixes else 0
    remaining = total - auto_fixed

    if total == 0:
        status = "CLEAN"
    elif analysis["summary"].get("P0", 0) > 0 or analysis["summary"].get("P1", 0) > 0:
        status = "CRITICAL"
    else:
        status = "NEEDS_ATTENTION"

    lines = []
    lines.append("## Self-Healing PR Review\n")
    lines.append(f"**Status:** `{status}`")
    lines.append(f"**Files Analyzed:** {analysis['files_analyzed']}")
    lines.append(f"**Issues Found:** {total} ({auto_fixed} auto-fixed, {remaining} remaining)\n")

    critical = [i for i in analysis["issues"] if i["category"] in ("P0", "P1")]
    lines.append("### Critical (P0-P1)")
    if critical:
        for issue in critical:
            emoji = CATEGORY_EMOJI[issue["category"]]
            cat = CATEGORY_LABELS[issue["category"]]
            lines.append(f"- {emoji} **[{cat}]** `{issue['file']}` L{issue['line']}: {issue['message']}")
            if issue.get("line_content"):
                lines.append(f"  ```\n  {issue['line_content']}\n  ```")
    else:
        lines.append("None found.\n")

    if fixes and fixes["total_fixes"] > 0:
        lines.append("\n### Auto-Fixed")
        for fix in fixes["fixes"]:
            lines.append(f"- `{fix['file']}`: {fix['fix']} ({fix['count']} instance(s))")
    else:
        lines.append("\n### Auto-Fixed")
        lines.append("No auto-fixes applied.\n")

    suggestions = [i for i in analysis["issues"] if i["category"] in ("P4", "P5", "P6", "P7")]
    lines.append("\n### Suggestions")
    if suggestions:
        for issue in suggestions:
            emoji = CATEGORY_EMOJI[issue["category"]]
            cat = CATEGORY_LABELS[issue["category"]]
            lines.append(f"- {emoji} **[{cat}]** `{issue['file']}` L{issue['line']}: {issue['message']}")
    else:
        lines.append("No suggestions.\n")

    lines.append("\n---")

    lines.append("\n### Summary")
    if status == "CLEAN":
        lines.append("This PR looks clean. No issues detected. Ship it!")
    elif status == "CRITICAL":
        p0 = analysis["summary"].get("P0", 0)
        p1 = analysis["summary"].get("P1", 0)
        lines.append(
            f"This PR has **{p0} security** and **{p1} bug** issue(s) that should be addressed before merging. "
            f"Please review the critical items above."
        )
    else:
        lines.append(
            f"This PR has {remaining} remaining issue(s) to review. "
            f"None are critical, but addressing them would improve code quality."
        )

    lines.append("\n<sub>Generated by Self-Healing PR Review</sub>")

    return "\n".join(lines)


def build_inline_comments(analysis: dict, head_sha: str) -> list:
    """Build inline review comments for file-specific issues."""
    comments = []
    seen = set()

    for issue in analysis["issues"]:
        key = (issue["file"], issue["line"], issue["message"])
        if key in seen:
            continue
        seen.add(key)

        emoji = CATEGORY_EMOJI.get(issue["category"], "")
        cat = CATEGORY_LABELS.get(issue["category"], issue["category"])

        comments.append({
            "path": issue["file"],
            "line": issue["line"],
            "body": f"{emoji} **[{cat}]** {issue['message']}",
        })

    return comments[:50]  # GitHub caps at ~60 inline comments per review


def post_review(repo: str, pr_number: int, body: str, comments: list, event: str = "COMMENT"):
    url = f"{GITHUB_API}/repos/{repo}/pulls/{pr_number}/reviews"

    payload = {
        "body": body,
        "event": event,
        "comments": comments,
    }

    resp = requests.post(url, headers=get_headers(), json=payload, timeout=30)

    if resp.status_code == 422 and comments:
        print("WARNING: Inline comments rejected (possibly stale diff). Posting body-only review.")
        payload["comments"] = []
        resp = requests.post(url, headers=get_headers(), json=payload, timeout=30)

    if resp.status_code == 403:
        print("WARNING: Review API returned 403. Falling back to PR comment.")
        return post_pr_comment(repo, pr_number, body)

    resp.raise_for_status()
    review = resp.json()
    print(f"Review posted: {review.get('html_url', 'N/A')}")
    return review


def post_pr_comment(repo: str, pr_number: int, body: str):
    """Fallback: post as a regular issue comment instead of a formal review."""
    url = f"{GITHUB_API}/repos/{repo}/issues/{pr_number}/comments"
    resp = requests.post(url, headers=get_headers(), json={"body": body}, timeout=30)
    resp.raise_for_status()
    comment = resp.json()
    print(f"Comment posted: {comment.get('html_url', 'N/A')}")
    return comment


def push_fixes(pr_dir: Path, repo: str, pr_number: int):
    repo_path = pr_dir / "repo"
    if not repo_path.exists():
        print("ERROR: Repo clone not found. Cannot push fixes.", file=sys.stderr)
        return False

    result = subprocess.run(
        ["git", "status", "--porcelain"],
        cwd=str(repo_path),
        capture_output=True,
        text=True,
    )

    if not result.stdout.strip():
        print("No changes to commit.")
        return False

    subprocess.run(
        ["git", "add", "-A"],
        cwd=str(repo_path),
        check=True,
        capture_output=True,
    )

    fixes_path = pr_dir / "fixes_applied.json"
    if fixes_path.exists():
        fixes = json.loads(fixes_path.read_text())
        fix_types = set(f["fix"] for f in fixes.get("fixes", []))
        summary = ", ".join(sorted(fix_types))
    else:
        summary = "auto-heal fixes"

    subprocess.run(
        ["git", "commit", "-m", f"fix: auto-heal - {summary}"],
        cwd=str(repo_path),
        check=True,
        capture_output=True,
        env={
            **os.environ,
            "GIT_AUTHOR_NAME": "Self-Healing Bot",
            "GIT_AUTHOR_EMAIL": "bot@self-healing.dev",
            "GIT_COMMITTER_NAME": "Self-Healing Bot",
            "GIT_COMMITTER_EMAIL": "bot@self-healing.dev",
        },
    )

    result = subprocess.run(
        ["git", "push"],
        cwd=str(repo_path),
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        print(f"ERROR: Push failed: {result.stderr}", file=sys.stderr)
        print("Falling back to report-only mode.")
        return False

    print("Fixes pushed to PR branch.")
    return True


def main():
    parser = argparse.ArgumentParser(description="Post review on a GitHub PR")
    parser.add_argument("--repo", required=True, help="owner/repo format")
    parser.add_argument("--pr", required=True, type=int, help="PR number")
    parser.add_argument("--analysis", required=True, help="Path to analysis.json")
    parser.add_argument("--fixes", help="Path to fixes_applied.json")
    parser.add_argument("--push-fixes", action="store_true", help="Push fix commits to PR branch")
    args = parser.parse_args()

    analysis_path = Path(args.analysis)
    if not analysis_path.exists():
        print(f"ERROR: {analysis_path} not found.", file=sys.stderr)
        sys.exit(1)

    analysis = json.loads(analysis_path.read_text())

    fixes = None
    if args.fixes:
        fixes_path = Path(args.fixes)
        if fixes_path.exists():
            fixes = json.loads(fixes_path.read_text())

    metadata_path = Path(f".tmp/pr-{args.pr}/metadata.json")
    head_sha = ""
    if metadata_path.exists():
        metadata = json.loads(metadata_path.read_text())
        head_sha = metadata.get("head_sha", "")

    if args.push_fixes:
        pr_dir = Path(f".tmp/pr-{args.pr}")
        pushed = push_fixes(pr_dir, args.repo, args.pr)
        if not pushed:
            print("Push failed or no changes. Posting report-only review.")

    body = build_review_body(analysis, fixes)
    comments = build_inline_comments(analysis, head_sha)

    has_critical = analysis["summary"].get("P0", 0) > 0 or analysis["summary"].get("P1", 0) > 0
    # GitHub blocks REQUEST_CHANGES on your own PRs, so fall back to COMMENT
    event = "COMMENT"

    print(f"\nPosting review on {args.repo}#{args.pr} (event: {event})...")
    post_review(args.repo, args.pr, body, comments, event)
    print("Done.")


if __name__ == "__main__":
    main()
